Update README.md
Ogury/ogury-sdk-sampleapp-ios pull request #6
Opened 2022-08-23 12:24 UTC by fernandpeng

2022-08-23 14:23 UTC, Pernic requested changes

2022-08-23 14:23 UTC, Pernic commented on README.md
> +	  - [Objective C](https://github.com/Ogury/ogury-sdk-sampleapp-ios/tree/master/Swift "Objective C")
remark (blocking) : https://github.com/Ogury/ogury-sdk-sampleapp-ios/tree/master/Swift "Objective C" are you sure

2022-08-23 15:05 UTC, fernandpeng commented on README.md
> +	  - [Objective C](https://github.com/Ogury/ogury-sdk-sampleapp-ios/tree/master/Swift "Objective C")
Fixed in 9cbb815

2022-08-31 10:15 UTC, Pernic approved these changes

2022-09-19 14:05 UTC, merged

2023-03-28 07:57 UTC, jesphinpt commented
Can anyone clarify this

How to support Ogury bidding source as part of AdMob Mediation Adapter in Applovin?

Steps:

- I am using Applovin mediation adapters in my app.
- Google AdMob mediation is available as part of the mediation adapters.
- I would like to add Ogury bidding source as part of Google AdMob
- Should I add Ogury Ads SDK to my app or is it not needed to support this integration.

2023-03-28 15:53 UTC, MarcoVieiraAntunes commented
Ogury can be used directly through Applovin's MAX mediation since we're a supported bidder - there is no need to use MAX mediating AdMob mediating Ogury.
The adapter is maintained by them, and can be found here: https://dash.applovin.com/documentation/mediation/ios/mediation-adapters?network=OGURY_PRESAGE_NETWORK .

2023-03-29 10:55 UTC, jesphinpt commented
If I add Ogury SDK to my app i am getting the below errors


```
Showing Recent Errors Only
Undefined symbol: _OBJC_CLASS_$_OGCInternal
Undefined symbol: _OBJC_CLASS_$_OguryAbstractLogMessage
Undefined symbol: _OBJC_CLASS_$_OguryLog
Undefined symbol: _OBJC_CLASS_$_OguryNetworkClient
Undefined symbol: _OBJC_CLASS_$_OguryNetworkRequestBuilder
Undefined symbol: _OBJC_CLASS_$_OguryOSLogger
Undefined symbol: _OBJC_CLASS_$_OguryPersistentEventBus
Undefined symbol: _OBJC_METACLASS_$_OguryAbstractLogMessage

```

2023-03-30 13:23 UTC, MarcoVieiraAntunes commented
First can you verify you imported manually all the below:

**OgurySdk.xcframework**
**OguryAds.xcframework
OguryChoiceManager.xcframework
OguryCore.xcframework
OMSDK_Ogury.xcframework** (it can be found in the OguryAds zip file)
 
Second, can you check that all frameworks are on mode "Do Not Embed":
 
<img width="559" alt="Screenshot 2023-03-28 at 15 54 32" src="https://user-images.githubusercontent.com/1671662/228849009-bec9dfbb-4ace-497f-9bb5-97aa82fd1bc5.png">

Third, can you add a -ObjC flag in the build settings:

<img width="489" alt="Screenshot 2023-03-28 at 15 54 17" src="https://user-images.githubusercontent.com/1671662/228849200-00f3a8db-6058-4592-ade7-abff3fb81c38.png">

Please let me know how it goes.

2023-03-30 14:41 UTC, jesphinpt commented
@MarcoVieiraAntunes I didn't found these all frameworks. Could you provide any zip for the above framework.

2023-03-31 13:12 UTC, MarcoVieiraAntunes commented
OgurySdk.xcframework
OguryAds.xcframework
OguryChoiceManager.xcframework
OguryCore.xcframework
OMSDK_Ogury.xcframework (it can be found in the OguryAds zip file)

https://binaries.ogury.co/release/ios/4.1.1/OgurySdk-4.1.1.tar.gz
https://binaries.ogury.co/release/ads-ios/3.4.1/OguryAds-3.4.1.tar.gz
https://binaries.ogury.co/release/choice-manager-ios/4.1.0/OguryChoiceManager-4.1.0.tar.gz
https://binaries.ogury.co/release/core-ios/1.3.0/OguryCore-1.3.0.tar.gz

2023-03-31 14:26 UTC, jesphinpt commented
The above works after adding the sdk's. Could you please let me know the above are the latest version frameworks of Ogury?
 
OguryAds-3.4.1 is 3.4.1
[OguryChoiceManager-4.1.0.tar.gz]
OguryCore 1.3.0

If you don't mind could you let mw know from where you get these links? I didn't found these like doc in the Ogury https://ogury-ltd.gitbook.io/ios/

2023-03-31 14:37 UTC, jesphinpt commented
@MarcoVieiraAntunes Could you please provide the OguryAdmobMediation Adapter as well. It would be helpful for us.

2023-03-31 14:58 UTC, MarcoVieiraAntunes commented
https://ogury-ltd.gitbook.io/release-notes/ios/ogury-adapters/admob

2023-03-31 15:04 UTC, jesphinpt commented
I have the GoogleMobileAdsSdk already. I am asking whether there is OguryMediationGoogleMobileAds framework which i need to download manually and add it to my Xcode libraries

2023-04-03 14:42 UTC, MarcoVieiraAntunes commented
https://binaries.ogury.co/release/mediation-google-mobiles-ads-ios/4.1.1.0/OguryMediationGoogleMobileAds-4.1.1.0.tar.gz

2023-04-04 09:57 UTC, jesphinpt commented
@MarcoVieiraAntunes We are getting the below errors after adding the OguryMediationGoogleAds.frames


```
OguryAds(OGAAdManager.o)
 "_objc_msgSend$systemTimeZone", referenced from:
   -[OGAAdServerMonitorRequestBuilder timeZone] in OguryAds(OGAAdServerMonitorRequestBuilder.o)
 "_objc_msgSend$initWithAdUnitId:bannerView:delegateDispatcher:adManager:notificationCenter:monitoringDispatcher:log:", referenced from:
   -[OGABannerAdInternalAPI initWithAdUnitId:bannerView:delegateDispatcher:] in OguryAds(OGABannerAdInternalAPI.o)
 "_objc_msgSend$objectForKeyedSubscript:", referenced from:
   -[OGWMonitoringInfo assetKey] in OgurySdk(OGWMonitoringInfo.o)
   -[OGWMonitoringInfo getValueForKey:] in OgurySdk(OGWMonitoringInfo.o)
   -[OGWMonitoringInfo putAll:] in OgurySdk(OGWMonitoringInfo.o)
   -[OGWMonitoringInfo containsAll:] in
OgurySdk(OGWMonitoringInfo.o)
   -[OGWMonitoringInfoFetcher populateAppVersion:] in OgurySdk(OGWMonitoringInfoFetcher.o)
   -[OGWMonitoringInfoSerializer deserialize:] in OgurySdk(OGWMonitoringInfoSerializer.o)
   -[OGAAdMonitorEvent asDisctionary] in OguryAds(OGAAdMonitorEvent.o)
   ...
 "_objc_msgSend$closeButtonBase64", referenced from:
   -[OGAMRAIDAdDisplayer setupViews] in OguryAds(OGAMRAIDAdDisplayer.o)
 "_objc_msgSend$appendMonitoringInfoAndSendIfNecessary:", referenced from:
   -[OGWWrapper startWithConfiguration:] in OgurySdk(OGWWrapper.o)
 "_objc_msgSend$hasPrefix:", referenced from:
   +[OGASKAdNetworkService sdkIsCompatibleWithSKAdNetwork] in OguryAds(OGASKAdNetworkService.o)
   -[OGAJSONModelError errorByPrependingKeyPathComponent:] in OguryAds(OGAJSONModelError.o)
   +[UIColor(OGAString) colorFromString:] in OguryAds(UIColor+OGAString.o)
   -[OGYJSONModelError errorByPrependingKeyPathComponent:] in OguryChoiceManager(OGYJSONModelError.o)
 "_objc_msgSend$closeWebView:", referenced from:
   -[OGAMraidCommandsHandler handleMraidCommand:] in OguryAds(OGAMraidCommandsHandler.o)
 "_objc_msgSend$omidSDK", referenced from:
   -[OGAOMIDService isOMIDActive] in OguryAds(OGAOMIDService.o)
   -[OGAOMIDService activateOMID] in OguryAds(OGAOMIDService.o)
 "_objc_msgSend$initWithBundle:", referenced from:
   -[OGAViewControllerOrientationHelper init] in OguryAds(OGAViewControllerOrientationHelper.o)
 "_objc_msgSend$eventNameFromShowErrorEvent:", referenced from:
   -[OGAMonitoringDispatcher sendShowErrorEvent:sessionId:adUnitId:] in OguryAds(OGAMonitoringDispatcher.o)
   -[OGAMonitoringDispatcher sendShowErrorEventAdExpired:sessionId:adUnitId:] in OguryAds(OGAMonitoringDispatcher.o)
 "_objc_msgSend$blackListViewControllers", referenced from:
   -[OGAAdConfiguration copyWithZone:] in OguryAds(OGAAdConfiguration.o)
   -[OGAThumbnailAdViewController viewControllerListUpdated] in OguryAds(OGAThumbnailAdViewController.o)
 "_objc_msgSend$name", referenced from:
   -[OGACloseAdAction performAction:error:] in OguryAds(OGACloseAdAction.o)
   -[OGAAdContainer state] in OguryAds(OGAAdContainer.o)
   -[OGAOpenStoreKitAction performAction:error:] in OguryAds(OGAOpenStoreKitAction.o)
   -[OGAUnloadAdAction performAction:error:] in OguryAds(OGAUnloadAdAction.o)
   -[OGADevice init] in OguryAds(OGADevice.o)
   -[OGADevice mapped] in OguryAds(OGADevice.o)
   -[OGAAdExposureController didReceiveKeyboardVisibilityDidChangeNotification:] in OguryAds(OGAAdExposureController.o)
   ...
 "_objc_msgSend$hasSentDisplayedDelegate", referenced from:
   -[OguryBannerAdDelegateDispatcher displayed] in OguryAds(OguryBannerAdDelegateDispatcher.o)
   -[OguryAdsOptinVideoDelegateDispatcher displayed] in OguryAds(OguryAdsOptinVideoDelegateDispatcher.o)
   -[OguryAdsThumbnailAdDelegateDispatcher displayed] in OguryAds(OguryAdsThumbnailAdDelegateDispatcher.o)
   -[OguryInterstitialAdDelegateDispatcher displayed] in OguryAds(OguryInterstitialAdDelegateDispatcher.o)
   -[OguryOptinVideoAdDelegateDispatcher displayed] in OguryAds(OguryOptinVideoAdDelegateDispatcher.o)
   -[OguryAdsBannerDelegateDispatcher displayed] in OguryAds(OguryAdsBannerDelegateDispatcher.o)
   -[OguryAdsInterstitialDelegateDispatcher displayed] in OguryAds(OguryAdsInterstitialDelegateDispatcher.o)
   ...
 "_objc_msgSend$setExpirationSource:", referenced from:
   -[OGAAdControllerFactory createControllerForAd:sequence:configuration:] in OguryAds(OGAAdControllerFactory.o)
   -[OGAExpirationContext initFrom:withExpirationTime:adPosition:] in OguryAds(OGAExpirationContext.o)
 "_objc_msgSend$storeProductViewController", referenced from:
   -[OGAStoreKitState loadStoreKitViewController:] in OguryAds(OGAStoreKitState.o)
   -[OGAStoreKitState display:error:] in OguryAds(OGAStoreKitState.o)
 "_objc_msgSend$sendExpirationTrackerEventForAd:", referenced from:
   -[OGAAdController isExpired] in OguryAds(OGAAdController.o)
 "_objc_msgSend$continueLoadAdAfterAdContentsPrepared:ads:error:", referenced from:
   ___54-[OGAAdManager continueLoadAdAfterAdSynced:ads:error:]_block_invoke in OguryAds(OGAAdManager.o)
 "_objc_msgSend$setIsStandardJSONType:", referenced from:
   -[OGAJSONModel __inspectProperties] in OguryAds(OGAJSONModel.o)
   -[OGYJSONModel __inspectProperties] in OguryChoiceManager(OGYJSONModel.o)
 "_objc_msgSend$integerForKey:", referenced from:
   -[OGWWrapper registerAttributionForSKAdNetwork] in OgurySdk(OGWWrapper.o)
 "_objc_msgSend$setActive:", referenced from:
   -[OGAMRAIDAdDisplayer deactivateConstrainIfFound:inView:] in OguryAds(OGAMRAIDAdDisplayer.o)
   -[OGAMRAIDAdDisplayer replaceOrAddConstraint:inView:] in OguryAds(OGAMRAIDAdDisplayer.o)
 "_objc_msgSend$viewProvider", referenced from:
   -[OGABannerAdContainerState display:error:] in OguryAds(OGABannerAdContainerState.o)
   -[OGAAdControllerFactory addTransitionsForBannerAd:configuration:builder:] in OguryAds(OGAAdControllerFactory.o)
   -[OGAAdConfiguration copyWithZone:] in OguryAds(OGAAdConfiguration.o)
 "_objc_msgSend$setIsCloseButtonHidden:", referenced from:
   -[OGAMRAIDAdDisplayer setupViews] in OguryAds(OGAMRAIDAdDisplayer.o)
   -[OGAMRAIDAdDisplayer setCloseButtonAsHidden:withDelay:] in OguryAds(OGAMRAIDAdDisplayer.o)
 "_objc_msgSend$setCampaignId:", referenced from:
   -[OGAAdMonitorEvent initWithTimestamp:sessionId:eventCode:event:dispatchType:adUnitId:campaignId:creativeId:detailsDictionary:errorType:errorContent:] in OguryAds(OGAAdMonitorEvent.o)
   -[OGABannerAdInternalAPI loadWithCampaignId:creativeId:size:] in OguryAds(OGABannerAdInternalAPI.o)
   -[OGABannerAdInternalAPI loadWithAdMarkup:size:] in OguryAds(OGABannerAdInternalAPI.o)
   -[OGAInterstitialAdInternalAPI loadWithCampaignId:creativeId:] in OguryAds(OGAInterstitialAdInternalAPI.o)
   -[OGAInterstitialAdInternalAPI loadWithAdMarkup:] in OguryAds(OGAInterstitialAdInternalAPI.o)
   -[OGAOptinVideoAdInternalAPI loadWithCampaignId:creativeId:] in OguryAds(OGAOptinVideoAdInternalAPI.o)
   -[OGAOptinVideoAdInternalAPI loadWithAdMarkup:] in OguryAds(OGAOptinVideoAdInternalAPI.o)
   ...
 "_objc_msgSend$setPreviousParentViewControllerBounds:", referenced from:
   -[OGABannerAdContainerState observeValueForKeyPath:ofObject:change:context:] in OguryAds(OGABannerAdContainerState.o)
 "_objc_msgSend$setExpirationDate:", referenced from:
   -[OGCInstanceToken removeExpirationDate] in OguryCore(OGCInstanceToken.o)
   -[OGCInstanceToken updateExpirationDate] in OguryCore(OGCInstanceToken.o)
 "_objc_msgSend$keyMapper", referenced from:
   -[OGAJSONModel __setup__] in OguryAds(OGAJSONModel.o)
   -[OGYJSONModel __setup__] in OguryChoiceManager(OGYJSONModel.o)
 "_objc_msgSend$destroy", referenced from:
   -[OguryAdsBanner close] in OguryAds(OguryAdsBanner.o)
   -[OguryBannerAd destroy] in OguryAds(OguryBannerAd.o)
 "_objc_msgSend$dateByAddingTimeInterval:", referenced from:
   -[OGAAdController isExpired] in OguryAds(OGAAdController.o)
   +[OGAConsentEventBus hasExpired:] in OguryAds(OGAConsentEventBus.o)
   -[OGAProfigManager isProfigExpired] in OguryAds(OGAProfigManager.o)
   ___49-[OGAMraidAdWebView startMRAIDProcessForContent:]_block_invoke.16 in OguryAds(OGAMraidAdWebView.o)
   _ [...]